### PR TITLE
style(dashboard): 💄style moveResponse

### PR DESCRIPTION
**Pull request by john-afolabi**
image

### CODE REVIEW

**Comment by rodrigograca31** [comment]
Dont we want to stick with that game-like font?

**Comment by rodrigograca31** [comment]
also, it seems your master wasnt fully updated so this makes a regression. it removes the skulls and the login redirect....

**Comment by john-afolabi** [comment]
The font wasn't very readable for the description. It works better for headers only. I'll fix the rest of the issues. Give me a few minutes

**Pull request merged**
